
version: '3.8'

services:
  api:
    build:
      context: ./src
      dockerfile: TaskManager.API/Dockerfile
    container_name: taskmanager_api
    ports:
      - "5000:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - taskmanager_network

  mysql:
    image: mysql:latest
    container_name: taskmanager_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - taskmanager_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  taskmanager_network:
    driver: bridge

volumes:
  db_data:
